import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Buy Me Samoa",
  description: "Generated by create next app",
  icons: {
    icon: [
      { rel: "icon", url: "/favicon.png", sizes: "32x32", type: "image/png" },
      { rel: "apple-touch-icon", url: "/favicon.png" },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={ `${geistSans.variable} ${geistMono.variable} antialiased` }>
        <Navbar />

        <div className="min-h-[81.5vh]">
        <div className="fixed top-0 left-0 z-[-2] min-h-screen w-full bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]">
</div>

          { children }
        </div>

        <Footer />
      </body>
    </html>
  );
}
